/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lettuce.demo;

import io.lettuce.core.RedisClient;
import io.lettuce.core.api.StatefulRedisConnection;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        RedisClient redisClient = RedisClient
                .create("redis://localhost:6379/");
        StatefulRedisConnection<String, String> connection
                = redisClient.connect();
        System.out.println(connection.isOpen());
    }
}
